#!/usr/bin/env zsh
#
# dif uses fzf to view diffs between mercurial revision chains.

local STATUS_PREFIX='hg status --no-status --color always --rev'
local DIFF_PREFIX='hg diff {} --color always --pager always --from'

: | fzf --ansi \
    --bind "start:reload($STATUS_PREFIX .)" \
    --preview="$DIFF_PREFIX . {}" \
    --bind "ctrl-w:change-prompt(working> )+reload($STATUS_PREFIX .)+change-preview($DIFF_PREFIX .)" \
    --bind "ctrl-v:change-prompt(parent> )+reload($STATUS_PREFIX '.^')+change-preview($DIFF_PREFIX '.^')" \
    --bind "ctrl-p:change-prompt(p4head> )+reload($STATUS_PREFIX p4head)+change-preview($DIFF_PREFIX p4head)" \
    --prompt 'working> ' \
    --query "${1:-}" \
    --header "ctrl-p: p4head | ctrl-v: parent | ctrl-w: working" \
    --header-first \
    --preview-window 'up,70%,border-bottom,~4'
