add_newline = true

format = """
${custom.pwd}\
$python\
$git_branch\
$git_status\
${custom.fig}\
$line_break\
$character"""

[custom.pwd]
format = "[($output)]($style) "
style = "bright-yellow"
command = 'print -P "%3~"'
when = true
disabled = false

[custom.fig]
format = "[$symbol ($output)]($style)"
symbol = ""
style = "bold white"
command = 'print -P "%B%F{7}$FIGSTATUS_CITC %F{3}$FIGSTATUS_MODIFIED%f%b"'
when = "[[ -n $FIGSTATUS_CITC ]]"
disabled = false

[character]
format = " $symbol "
success_symbol = ">"
error_symbol = ">"

[python]
format = '[($symbol $virtualenv)]($style)'
style = 'fg:#E7D60A'
symbol = ''
disabled = false

[directory]
format = "[$path]($style) "
style = "bright-yellow"
read_only = " "
read_only_style = "red"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = ""
home_symbol = "~"
disabled = true

[git_branch]
format = "[$symbol $branch]($style)"
symbol = ""
style = "white"
disabled = true

[git_status]
format = '([\[$all_status\]]($style))'
style = "yellow"
conflicted = "="
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "%"
deleted = "-"
disabled = true
