add_newline = true

format = '''$python
$directory$git_branch$git_status${custom.fig_citc}${custom.fig_cl}${custom.fig_status}
 > 
'''

[custom.fig_citc]
command = "pwd | cut -d'/' -f6"
symbol = " "
when = """ test "$PWD" "=~" "/google/src/cloud/[^/]+/[^/]+/.*" """
style = 'bold blue'

[custom.fig_cl]
command = "hg figstatus | tail -1"
format = "[at $output]($style)"
style = "bold blue"
when = """ test "$PWD" "=~" "/google/src/cloud/[^/]+/[^/]+/.*" """
disabled = false

[custom.fig_status]
command = "hg figstatus | head -1"
format = " [$output]($style)"
style = "bold red"
when = """ test "$PWD" "=~" "/google/src/cloud/[^/]+/[^/]+/.*" """
disabled = false


[python]
format = '[($symbol $virtualenv) ]($style)'
style = 'fg:#E7D60A'
symbol = ' '

[kubernetes]
disabled = false
format = '[$symbol $context]($style) '
style = 'cyan'
symbol = 'ﴱ '

[gcloud]
disabled = true
format = '[$symbol $project]($style)'
style = 'blue bold'
symbol = ' '

[git_branch]
symbol = "  "

[git_status]
format = '([$all_status$all_behind]($style) )'



[aws]
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[cmd_duration]
disabled = true

[dart]
symbol = " "

[directory]
disabled = false
read_only = " "
#style = "green"

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "
disabled = false

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
