add_newline = true

format = """

$directory\
$python\
$git_branch\
$git_status\
${custom.fig}\
$line_break\
$character"""

[custom.fig]
format = "[$symbol ($output)]($style) "
symbol = ""
style = "bold white"
command = 'print -P "%B%F{7}$G3DIR at $FIG_CL%f %F{3}$FIG_MODIFIED%f%b"'
when = "test -n $G3DIR"
disabled = true

[character]
format = " $symbol "
success_symbol = ">"
error_symbol = ">"

[python]
format = '[($symbol $virtualenv)]($style) '
style = 'fg:#E7D60A'
symbol = ''
disabled = false

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold yellow"
read_only = " "
read_only_style = "red"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = ""
home_symbol = "~"
disabled = false

[git_branch]
format = "[$symbol $branch]($style) "
symbol = ""
style = "white"
disabled = false

[git_status]
format = '([\[$all_status\]]($style)) '
style = "yellow"
conflicted = "="
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "%"
deleted = "-"
